builds:
  - id: darwin-amd64
    main: ./
    binary: golang-cross
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}