name: Pull Request Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test

    steps:
      - uses: actions/checkout@v2
        with:
          go-version: '1.17.6'

      - name: Build
        run: make build

      - name: Run tests
        run: make check
      - name: Upload coverage reports to Codecov with GitHub Action
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN} -f coverage.txt -F unit
          ./codecov -t ${CODECOV_TOKEN} -f integration_coverage.txt -F integration
