name: tag

on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
        with:
          go-version: '1.17.6'
      - name: Build
        run: make build
      - name: Run tests
        run: make check
      - name: Upload coverage reports to Codecov with GitHub Action
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN} -f coverage.txt -F unit
          ./codecov -t ${CODECOV_TOKEN} -f integration_coverage.txt -F integration

  tag:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: tag
        id: tag_generator
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          bump_each_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: git
        run: |
          git tag ${{ steps.tag_generator.outputs.version_tag }}
          git push origin --tags

  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.6'

      - name: Set up release environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' >> .release-env

      - name: Run GoReleaser
        run: make release
